### ISSUE TITLE
GraphSage reproducibility

### ISSUE THREAD

**Issue by diegovalsesia** [graphdeeplearning/benchmarking-gnns#12]
Hi, I am trying to reproduce the results on the ZINC dataset with GraphSAGE but I keep getting test MAE values around 0.58 instead of the 0.43 reported in the paper, with all settings at default (L=4 layers). I am also getting a slightly different number of parameters (104167 instead of 105301). The other networks work fine.

Thanks!

**Comment by vijaydwivedi75** [comment]
Hi @diegovalsesia, Thanks a lot for raising this issue.

Indeed, due to a recent update, the batch norm flag remained unlinked with the batch norm flag from the respective config files of the dataset. This is why, when you ran the code, the number of parameters for ZINC was lesser than the number reported in the paper.

I have fixed the bug. You should be able to get the original results now. Besides, please run for ZINC for 4 times with the seeds mentioned in the scripts to reproduce (almost) the exact result.

Best,
Vijay

**Comment by vijaydwivedi75** [comment]
Moreover, we aim to keep updating (also, include contributions from other users) the code in the master branch. 

Therefore, to reproduce the results of the arXiv v1 paper, there is a separate branch with the earlier code. https://github.com/graphdeeplearning/benchmarking-gnns/tree/arXivV1

**Comment by diegovalsesia** [comment]
Now it's working. Thanks a lot
