### ISSUE TITLE
Adjacency Matrix for SBM_Cluster Training

### ISSUE THREAD

**Issue by Lavenderjiang** [graphdeeplearning/benchmarking-gnns#19]
From my understanding, you randomly generated 10k graphs of random sizes for training. 
For training with a citation network, a single graph A is passed into the GNN. 
**For training with SBM_Cluster, do you combine these randomly generated graphs (A_{i}) into a big diagonal block matrix?** (like how we aggregate graphs for a graph classification problem, but without the pooling layer?)
![IMG_0896](https://user-images.githubusercontent.com/22594040/80221532-68dc7380-8613-11ea-9ee3-f269ece97e67.jpg)

**Comment by vijaydwivedi75** [comment]
Hi @Lavenderjiang, thanks for your question!

Yes, we use the similar batching of graphs for the SBMs data. Please check the collate function code [here](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/data/SBMs.py#L152).

Also, the pooling/readout is not used for SBMs since node-level task.

**Comment by chaitjo** [comment]
In general, today in citation network tasks, the individual graph is huge (1000s of nodes), but you usually have only one graph to learn on. We built datasets where individual graphs are medium scale (100s of nodes) and we can learn from multiple such medium-scale graphs.

**Comment by Lavenderjiang** [comment]
Thanks Vijay and Chait! This answers my question :)
