### ISSUE TITLE
Questin About semisupervised_MNIST_CIFAR10 dataset

### ISSUE THREAD

**Issue by Austinzhenghua** [graphdeeplearning/benchmarking-gnns#64]
I have a question about these two datasets. there are three subset trainset, valset, and testset. How to combine these datasets into one whole set? Thank you.

**Comment by Austinzhenghua** [comment]
@vijaydwivedi75 I have a question about these two datasets. there are three subset trainset, valset, and testset. How to combine these datasets into one whole set? Because I want to do clustering with the whole graphs Thank you.

**Comment by chaitjo** [comment]
Hi @Austinzhenghua, thanks for your interest. You can probably simply concatenate the data and label lists for the train, val and test sets before preparing a data loader for them. That should work (unless I misunderstood your Q.).

**Comment by Austinzhenghua** [comment]
Hi, @chaitjo Thanks for your reply, I am super interested in this work, it's amazing and quite significant. But the  DGL format graph is quite complicated for me (as a beginner). As far as I know,  you load the dataset here:
![image](https://user-images.githubusercontent.com/34674970/125964769-0154cf24-532f-4cf2-b5d7-4e038cace7b2.png)
So, How to concatenate the f[0], f[1] and f[2]? Could you  pls give me some exact method (or code), Maybe self.all = f[0]+f[1]+f[2] can not work. Thanks very much! Have a nice day!

**Comment by chaitjo** [comment]
Thank you for your comment, hope it is helpful to your future research. 

I believe you are right. Each of train, val, and test are lists of (graph, label) tuples. Thus, you can just concatenate the lists together. The DGL format batch of graphs is only created when the collate function is called during dataloading, i.e. during the training/testing loop when we iterate over data in mini-batches. Otherwise, the dataset object just stores the data points in a list.

Hope it helps. I would suggest working through DGL tutorials before working with this codebase.

**Comment by Austinzhenghua** [comment]
> Thank you for your comment, hope it is helpful to your future research.
> 
> I believe you are right. Each of train, val, and test are lists of (graph, label) tuples. Thus, you can just concatenate the lists together. The DGL format batch of graphs is only created when the collate function is called during dataloading, i.e. during the training/testing loop when we iterate over data in mini-batches. Otherwise, the dataset object just stores the data points in a list.
> 
> Hope it helps. I would suggest working through DGL tutorials before working with this codebase.

OH, Thank you so much, I know how to do it with your kind help. Wish you have a good day!

**Comment by chaitjo** [comment]
Great, closing the issue.
