### ISSUE TITLE
The possibility of having 2D node features

### ISSUE THREAD

**Issue by jamzad** [graphdeeplearning/benchmarking-gnns#69]
Hello and thanks for sharing the code of your amazing paper.

With the current implementation of graphs in DGL, is it possible to have 2D feature for nodes and 1D features for edges? I'm familiar with the super pixel concept, but if we want to use image patches directly as node features (without flattening) , how we should change the implementation?

Thanks you very much

**Comment by chaitjo** [comment]
Hi @jamzad, yes, it should be possible to have 2D features for nodes as long as the 2D features have a consistent dimension (in your superpixel example). You can then apply a standard ConvNet on the 2D features in order to 'flatten' them into 1D features before inputting that into the GNN layers. Hope it helps!
